* Added imlib2 support(experimental).   (Thanks to Frederic Heulin). * x_window.c(x_window_receive_event,MotionNotify):   Check if button is pressed before win->button_motion is called.   (Thanks to shirai hideyuki)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -21561,6 +21561,56 @@ fi
 	IMAGELIB_LIBS="`imlib-config --libs`"
 	IMAGELIB_NAME=imlib
 	;;
+imlib2)
+	# Extract the first word of "imlib-config", so it can be a program name with args.
+set dummy imlib-config; ac_word=$2
+{ $as_echo "$as_me:$LINENO: checking for $ac_word" >&5
+$as_echo_n "checking for $ac_word... " >&6; }
+if test "${ac_cv_prog_imlib_config+set}" = set; then
+  $as_echo_n "(cached) " >&6
+else
+  if test -n "$imlib_config"; then
+  ac_cv_prog_imlib_config="$imlib_config" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_prog_imlib_config="yes"
+    $as_echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  test -z "$ac_cv_prog_imlib_config" && ac_cv_prog_imlib_config="no"
+fi
+fi
+imlib_config=$ac_cv_prog_imlib_config
+if test -n "$imlib_config"; then
+  { $as_echo "$as_me:$LINENO: result: $imlib_config" >&5
+$as_echo "$imlib_config" >&6; }
+else
+  { $as_echo "$as_me:$LINENO: result: no" >&5
+$as_echo "no" >&6; }
+fi
+
+
+	if test "x$imlib2_config" = "xno" ; then
+		echo ""
+		echo "** ERROR **"
+		echo "Could not find imlib2-config."
+		echo ""
+		exit 1
+	fi
+	IMAGELIB_CFLAGS="`imlib2-config --cflags` -DUSE_IMLIB"
+	IMAGELIB_LIBS="`imlib2-config --libs`"
+	IMAGELIB_NAME=imlib2
+	;;
 gdk-pixbuf)
 
 
diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -100,6 +100,19 @@ imlib)
 	IMAGELIB_LIBS="`imlib-config --libs`"
 	IMAGELIB_NAME=imlib
 	;;
+imlib2)
+	AC_CHECK_PROG(imlib_config,imlib-config,yes,no)
+	if test "x$imlib2_config" = "xno" ; then
+		echo ""
+		echo "** ERROR **"
+		echo "Could not find imlib2-config."
+		echo ""
+		exit 1
+	fi
+	IMAGELIB_CFLAGS="`imlib2-config --cflags` -DUSE_IMLIB"
+	IMAGELIB_LIBS="`imlib2-config --libs`"
+	IMAGELIB_NAME=imlib2
+	;;
 gdk-pixbuf)
 	PKG_CHECK_MODULES(IMAGELIB, gdk-pixbuf-2.0, [
 		IMAGELIB_NAME=gdk
