* inputmethod/iiimf/im_iiimf.c: minor code cleanup. * inputmethod/iiimf/aux.c: minor code cleanup.
* configure.in: IIIMF plugin cannot be used with --with-libltdl.

* xwindow/x_term_manager.c (client_connected):
  - argv[argc + 1] = NULL ;   --->   argv[argc] = NULL ;
  - "mlclient --foo=bar" does not work. fixed.

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -392,7 +392,7 @@ AC_SUBST(UIM_CFLAGS)
 AC_SUBST(UIM_LIBS)
 
 #
-# --- iiimf ---
+# --- IIIMF ---
 #
 AC_ARG_ENABLE(iiimf,
 	[  --enable-iiimf          IIIMF (Experimental) [default=disabled]],
@@ -420,9 +420,14 @@ if test "x$iiimf" = xyes ; then
 		MAKE_DIRS="inputmethod/iiimf ${MAKE_DIRS}"
 		OUTPUT_FILES="inputmethod/iiimf/Makefile ${OUTPUT_FILES}"
 		if test "x$with_libltdl" != xno ; then
-			DL_LIBS_IM="-dlopen \$(top_builddir)/inputmethod/iiimf/libim-iiimf.la ${DL_LIBS_IM}"
+			echo ""
+			echo "** ERROR **"
+			echo " IIIMF plugin couldn't be used with libltdl."
+			echo ""
+			exit 1
+		else
+			input_methods_result="$input_methods_result IIIMF"
 		fi
-		input_methods_result="$input_methods_result IIIMF"
 		AC_CHECK_LIB(iiimcf, iiimcf_create_hotkey_notify_event,
 			[
 			IIIMF_CFLAGS="$IIIMF_CFLAGS -DHAVE_HOTKEY_NOTFY_EVENT"
