* doc/ja/README.fb, doc/en/README.fb: Updated. * fb/x.h, fb/x_display, fb/x_simple_sb_view.c, fb/x_window.c,   x_screen_manager.c, x_scrollbar.c, x_sample_sb_view_fb.c,   x_sb_view_factory.c, configure.in, dexport-fb.map:   simple and sample scrollbars are supported in framebuffer. * win32/x_xic.c: Typo is fixed.

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -52,15 +52,19 @@ AC_SUBST(SOCK_LIBS)
 
 AC_PATH_XTRA
 
-if test "$with_gnu_ld" = "yes" ; then
-	DEXPORT="-Wl,--version-script=\$(VPATH)/dexport.map"
-fi
-AC_SUBST(DEXPORT)
-
 AC_ARG_WITH(gui,
 	[  --with-gui@<:@=ARG@:>@        gui library(xlib|win32)],
 	gui=$with_gui)
 	
+if test "$with_gnu_ld" = "yes" ; then
+	if test "$gui" = "fb" ; then
+		DEXPORT="-Wl,--version-script=\$(VPATH)/dexport-fb.map"
+	else
+		DEXPORT="-Wl,--version-script=\$(VPATH)/dexport.map"
+	fi
+fi
+AC_SUBST(DEXPORT)
+
 AC_ARG_ENABLE(debug,
 	[  --enable-debug          debug @<:@default=disabled@:>@],
 	debug=$enable_debug)
@@ -822,10 +826,10 @@ AC_ARG_WITH(scrollbars,
 	fi
 	])
 
-if test "$gui" = "fb" ; then
-	scrollbars=""
-else
-	scrollbars=`echo ${scrollbars} | sed 's/,/ /g'`
+scrollbars=`echo ${scrollbars} | sed 's/,/ /g'`
+
+if test "$gui" = "fb" -a "$scrollbars" != "" ; then
+	DL_LIBS_SB="-export-dynamic ${DL_LIBS_SB}"
 fi
 
 for scrollbar in ${scrollbars} ; do
@@ -862,22 +866,24 @@ pixmap_engine)
 		echo ""
 		exit 1
 	fi
-	if test "$have_gdk_pixbuf1" = "yes" -o "$have_gdk_pixbuf2" = "yes" ; then
-		MAKE_DIRS="contrib/scrollbar/pixmap_engine ${MAKE_DIRS}"
-		OUTPUT_FILES="contrib/scrollbar/pixmap_engine/Makefile contrib/scrollbar/pixmap_engine/sample3/Makefile ${OUTPUT_FILES}"
-		if test "x$with_libltdl" != "xno" ; then
-			DL_LIBS_SB="-export-dynamic -dlopen \$(top_builddir)/contrib/scrollbar/pixmap_engine/libpixmap_engine.la ${DL_LIBS_SB}"
+	if test "$gui" = "xlib" ; then
+		if test "$have_gdk_pixbuf1" = "yes" -o "$have_gdk_pixbuf2" = "yes" ; then
+			MAKE_DIRS="contrib/scrollbar/pixmap_engine ${MAKE_DIRS}"
+			OUTPUT_FILES="contrib/scrollbar/pixmap_engine/Makefile contrib/scrollbar/pixmap_engine/sample3/Makefile ${OUTPUT_FILES}"
+			if test "x$with_libltdl" != "xno" ; then
+				DL_LIBS_SB="-export-dynamic -dlopen \$(top_builddir)/contrib/scrollbar/pixmap_engine/libpixmap_engine.la ${DL_LIBS_SB}"
+			else
+				DL_LIBS_SB="-export-dynamic ${DL_LIBS_SB}"
+			fi
+			SB_CFLAGS="-DSUPPORT_PIXMAP_ENGINE"
+			scrollbars_result="$scrollbars_result $scrollbar"
 		else
-			DL_LIBS_SB="-export-dynamic ${DL_LIBS_SB}"
+			echo ""
+			echo "** ERROR **"
+			echo "To use pixmap_engine for scrollbar, you need gdk-pixbuf library."
+			echo ""
+			exit 1
 		fi
-		SB_CFLAGS="-DSUPPORT_PIXMAP_ENGINE"
-		scrollbars_result="$scrollbars_result $scrollbar"
-	else
-		echo ""
-		echo "** ERROR **"
-		echo "To use pixmap_engine for scrollbar, you need gdk-pixbuf library."
-		echo ""
-		exit 1
 	fi
 	;;
 *)
