* xlib/x_window.c: size_hints.min_width and min_height are fixed. * gtk/INSTALL: Updated. * configure.in: vte-2.91 is supported. * vte.c:   - vte-2.91 is supported. (Experimental)   - Following functions are implemented.     vte_terminal_feed     vte_terminal_feed_child     vte_terminal_feed_child_binary     vte_terminal_set_scroll_on_output     vte_terminal_write_contents(_sync)   - window.width_inc,min_width,height_inc,min_height are reset in     vte_terminal_set_font_from_string().   - g_object_ref(terminal->pvt->pty) is replaced by g_object_ref(pty) in     vte_terminal_set_pty(_object)(). * kik_pty_helper.c:   - kill(pty_helper_pid, SIGTERM) isn't called by child processes.   - setsid() and setpgid() are moved after reopening pty like vte-0.39.1/src/pty.c. * version.h.in: 3.4.3 -> 3.4.3post

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -21605,6 +21605,76 @@ if test -n "$VTE_CFLAGS"; then
     pkg_cv_VTE_CFLAGS="$VTE_CFLAGS"
  elif test -n "$PKG_CONFIG"; then
     if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"vte-2.91\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "vte-2.91") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_VTE_CFLAGS=`$PKG_CONFIG --cflags "vte-2.91" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+if test -n "$VTE_LIBS"; then
+    pkg_cv_VTE_LIBS="$VTE_LIBS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"vte-2.91\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "vte-2.91") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_VTE_LIBS=`$PKG_CONFIG --libs "vte-2.91" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        VTE_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors "vte-2.91" 2>&1`
+        else
+	        VTE_PKG_ERRORS=`$PKG_CONFIG --print-errors "vte-2.91" 2>&1`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$VTE_PKG_ERRORS" >&5
+
+	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+                have_vte=no
+elif test $pkg_failed = untried; then
+	have_vte=no
+else
+	VTE_CFLAGS=$pkg_cv_VTE_CFLAGS
+	VTE_LIBS=$pkg_cv_VTE_LIBS
+        { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+$as_echo "yes" >&6; }
+	have_vte=yes
+fi
+		if test "$have_vte" = "yes" ; then
+			LIBVTE_SUFFIX=2_91
+		else
+
+pkg_failed=no
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for VTE" >&5
+$as_echo_n "checking for VTE... " >&6; }
+
+if test -n "$VTE_CFLAGS"; then
+    pkg_cv_VTE_CFLAGS="$VTE_CFLAGS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
     { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"vte-2.90\""; } >&5
   ($PKG_CONFIG --exists --print-errors "vte-2.90") 2>&5
   ac_status=$?
@@ -21663,7 +21733,8 @@ else
 $as_echo "yes" >&6; }
 	have_vte=yes
 fi
-		LIBVTE_SUFFIX=2_90
+			LIBVTE_SUFFIX=2_90
+		fi
 
 	else
 
