* 3.1.1 released.   (tag "rel-3_1_1") * configure.in, mlterm.spec, xwindow/version.h.in,   doc/en/ReleaseNote: updated for 3.1.1. * configure.in: If xlib is not found, configure script exits. * kik_pty_streams.c:   <kik_config.h> is included instead of <kik_def.h> to   fix segfault in 64bit Linux. * mlterm.1, mlclient.1: Updated. * x_main_config.c, main_loop.c:   --sep, --button3, --clip, --restart and --logmsg options are   moved from main_loop.c to x_main_config.c to enable to specify   them for mlclient.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -19812,9 +19812,17 @@ fi
 	CYGPATHW=echo
 	if test "$gui" != "xlib" ; then
 		if test "$gui" != "" ; then
-			echo "$gui is not supported in ${host_os}. Use xlib."
+			echo "$gui is not supported in ${host_os}. xlib is used instead."
 		fi
 		gui="xlib"
+	fi
+	# $have_x is defined in AC_PATH_XTRA.
+	if test "$have_x" != "yes" ; then
+		echo ""
+		echo "** ERROR **"
+		echo "Could not find xlib."
+		echo ""
+		exit 1
 	fi
 	;;
 esac
@@ -22899,7 +22907,7 @@ fi
 
 # Define the identity of the package.
  PACKAGE=mlterm
- VERSION=3.1.0
+ VERSION=3.1.1
 
 
 cat >>confdefs.h <<_ACEOF
diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -115,9 +115,17 @@ cygwin*)
 	CYGPATHW=echo
 	if test "$gui" != "xlib" ; then
 		if test "$gui" != "" ; then
-			echo "$gui is not supported in ${host_os}. Use xlib."
+			echo "$gui is not supported in ${host_os}. xlib is used instead."
 		fi
 		gui="xlib"
+	fi
+	# $have_x is defined in AC_PATH_XTRA.
+	if test "$have_x" != "yes" ; then
+		echo ""
+		echo "** ERROR **"
+		echo "Could not find xlib."
+		echo ""
+		exit 1
 	fi
 	;;
 esac
@@ -900,7 +908,7 @@ if test "$optimize_redrawing" = "yes" ; then
 fi
 
 # gettext
-AM_INIT_AUTOMAKE(mlterm,3.1.0)
+AM_INIT_AUTOMAKE(mlterm,3.1.1)
 AM_GNU_GETTEXT([external])
 
 # XXX(maybe not portable)
