* configure.in: m17nlib is checked by PKG_CHECK_MODULES(). * mc_im.c: libim-*-sdl2.so is supported if gui is "sdl2".

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -853,7 +853,7 @@ IBUS_LIBS
 IBUS_CFLAGS
 M17NLIB_LIBS
 M17NLIB_CFLAGS
-m17nlib
+m17n_config
 IIIMCF_LIBS
 IIIMCF_CFLAGS
 UIM_LIBS
@@ -1129,6 +1129,8 @@ UIM_CFLAGS
 UIM_LIBS
 IIIMCF_CFLAGS
 IIIMCF_LIBS
+M17NLIB_CFLAGS
+M17NLIB_LIBS
 IBUS_CFLAGS
 IBUS_LIBS
 FCITX_CFLAGS
@@ -1871,6 +1873,10 @@ Some influential environment variables:
   IIIMCF_CFLAGS
               C compiler flags for IIIMCF, overriding pkg-config
   IIIMCF_LIBS linker flags for IIIMCF, overriding pkg-config
+  M17NLIB_CFLAGS
+              C compiler flags for M17NLIB, overriding pkg-config
+  M17NLIB_LIBS
+              linker flags for M17NLIB, overriding pkg-config
   IBUS_CFLAGS C compiler flags for IBUS, overriding pkg-config
   IBUS_LIBS   linker flags for IBUS, overriding pkg-config
   FCITX_CFLAGS
@@ -4720,7 +4726,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4723 "configure"' > conftest.$ac_ext
+  echo '#line 4729 "configure"' > conftest.$ac_ext
   if { { eval echo "\"\$as_me\":${as_lineno-$LINENO}: \"$ac_compile\""; } >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7288,11 +7294,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7291: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7297: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7295: \$? = $ac_status" >&5
+   echo "$as_me:7301: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7578,11 +7584,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7581: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7587: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7585: \$? = $ac_status" >&5
+   echo "$as_me:7591: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7682,11 +7688,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7685: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7691: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7689: \$? = $ac_status" >&5
+   echo "$as_me:7695: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -9707,7 +9713,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9710 "configure"
+#line 9716 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -9807,7 +9813,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9810 "configure"
+#line 9816 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12148,11 +12154,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12151: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12157: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12155: \$? = $ac_status" >&5
+   echo "$as_me:12161: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12252,11 +12258,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12255: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12261: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12259: \$? = $ac_status" >&5
+   echo "$as_me:12265: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -13835,11 +13841,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13838: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13844: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13842: \$? = $ac_status" >&5
+   echo "$as_me:13848: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13939,11 +13945,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13942: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13948: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13946: \$? = $ac_status" >&5
+   echo "$as_me:13952: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16100,11 +16106,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16103: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16109: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16107: \$? = $ac_status" >&5
+   echo "$as_me:16113: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16390,11 +16396,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16393: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16399: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16397: \$? = $ac_status" >&5
+   echo "$as_me:16403: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16494,11 +16500,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16497: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16503: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16501: \$? = $ac_status" >&5
+   echo "$as_me:16507: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -23372,11 +23378,11 @@ if test "x$m17nlib" != xno ; then
 set dummy m17n-config; ac_word=$2
 { $as_echo "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
 $as_echo_n "checking for $ac_word... " >&6; }
-if ${ac_cv_prog_m17nlib+:} false; then :
+if ${ac_cv_prog_m17n_config+:} false; then :
   $as_echo_n "(cached) " >&6
 else
-  if test -n "$m17nlib"; then
-  ac_cv_prog_m17nlib="$m17nlib" # Let the user override the test.
+  if test -n "$m17n_config"; then
+  ac_cv_prog_m17n_config="$m17n_config" # Let the user override the test.
 else
 as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
 for as_dir in $PATH
@@ -23385,7 +23391,7 @@ do
   test -z "$as_dir" && as_dir=.
     for ac_exec_ext in '' $ac_executable_extensions; do
   if as_fn_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
-    ac_cv_prog_m17nlib="yes"
+    ac_cv_prog_m17n_config="yes"
     $as_echo "$as_me:${as_lineno-$LINENO}: found $as_dir/$ac_word$ac_exec_ext" >&5
     break 2
   fi
@@ -23393,23 +23399,97 @@ done
   done
 IFS=$as_save_IFS
 
-  test -z "$ac_cv_prog_m17nlib" && ac_cv_prog_m17nlib="no"
+  test -z "$ac_cv_prog_m17n_config" && ac_cv_prog_m17n_config="no"
 fi
 fi
-m17nlib=$ac_cv_prog_m17nlib
-if test -n "$m17nlib"; then
-  { $as_echo "$as_me:${as_lineno-$LINENO}: result: $m17nlib" >&5
-$as_echo "$m17nlib" >&6; }
+m17n_config=$ac_cv_prog_m17n_config
+if test -n "$m17n_config"; then
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: $m17n_config" >&5
+$as_echo "$m17n_config" >&6; }
 else
   { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
 $as_echo "no" >&6; }
 fi
 
 
-	m17n_saved_libs="$LIBS"
-	M17NLIB_LIBS=`m17n-config --libs`
-	LIBS="$LIBS $M17NLIB_LIBS"
-	{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for minput_open_im in -lm17n" >&5
+	if test "$m17n_config" = "yes"; then
+		M17NLIB_LIBS=`m17n-config --libs`
+		M18NLIB_CFLAGS=`m17n-config --cflags`
+		m17nlib=yes
+	else
+
+pkg_failed=no
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for M17NLIB" >&5
+$as_echo_n "checking for M17NLIB... " >&6; }
+
+if test -n "$M17NLIB_CFLAGS"; then
+    pkg_cv_M17NLIB_CFLAGS="$M17NLIB_CFLAGS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"m17n-shell\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "m17n-shell") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_M17NLIB_CFLAGS=`$PKG_CONFIG --cflags "m17n-shell" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+if test -n "$M17NLIB_LIBS"; then
+    pkg_cv_M17NLIB_LIBS="$M17NLIB_LIBS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"m17n-shell\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "m17n-shell") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_M17NLIB_LIBS=`$PKG_CONFIG --libs "m17n-shell" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        M17NLIB_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors "m17n-shell" 2>&1`
+        else
+	        M17NLIB_PKG_ERRORS=`$PKG_CONFIG --print-errors "m17n-shell" 2>&1`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$M17NLIB_PKG_ERRORS" >&5
+
+	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+                m17nlib=no
+elif test $pkg_failed = untried; then
+	m17nlib=no
+else
+	M17NLIB_CFLAGS=$pkg_cv_M17NLIB_CFLAGS
+	M17NLIB_LIBS=$pkg_cv_M17NLIB_LIBS
+        { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+$as_echo "yes" >&6; }
+	m17nlib=yes
+fi
+	fi
+
+  if test "$m17nlib" = "yes"; then
+		m17n_saved_libs="$LIBS"
+		LIBS="$LIBS $M17NLIB_LIBS"
+		{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for minput_open_im in -lm17n" >&5
 $as_echo_n "checking for minput_open_im in -lm17n... " >&6; }
 if ${ac_cv_lib_m17n_minput_open_im+:} false; then :
   $as_echo_n "(cached) " >&6
@@ -23447,17 +23527,17 @@ fi
 $as_echo "$ac_cv_lib_m17n_minput_open_im" >&6; }
 if test "x$ac_cv_lib_m17n_minput_open_im" = xyes; then :
 
-		M17NLIB_CFLAGS="`m17n-config --cflags`"
-		MAKE_DIRS="inputmethod/m17nlib ${MAKE_DIRS}"
-		OUTPUT_FILES="inputmethod/m17nlib/Makefile ${OUTPUT_FILES}"
-		if test "x$with_libltdl" != xno ; then
-			DL_LIBS_IM="-dlopen \$(top_builddir)/inputmethod/m17nlib/libim-m17nlib.la ${DL_LIBS_IM}"
-		fi
-		input_methods_result="$input_methods_result m17nlib"
+			MAKE_DIRS="inputmethod/m17nlib ${MAKE_DIRS}"
+			OUTPUT_FILES="inputmethod/m17nlib/Makefile ${OUTPUT_FILES}"
+			if test "x$with_libltdl" != xno ; then
+				DL_LIBS_IM="-dlopen \$(top_builddir)/inputmethod/m17nlib/libim-m17nlib.la ${DL_LIBS_IM}"
+			fi
+			input_methods_result="$input_methods_result m17nlib"
 
 fi
 
-	LIBS="$m17n_saved_libs"
+		LIBS="$m17n_saved_libs"
+	fi
 fi
 
 
